#!/usr/bin/env bash
: "${VERBOSITY:=10}"

useage () {
  echo "$0 repo_to_clone"
}

if [[ $# -eq 1 ]]; then
  TARGET_REPO=$1
  TARGET_DIR=$(echo "$1"|awk -F'/' '{print $NF}'|sed 's/^\(.*\)\.git/\1/')
elif [[ $# -eq 2 ]]; then
  TARGET_REPO=$1
  TARGET_DIR=$2
else 
  useage
  exit 1
fi

if [[ ${VERBOSITY} -gt 0 ]]
then
  echo "Cloning ${TARGET_REPO} into ${TARGET_DIR}"
  mkdir -v "${TARGET_DIR}"
else
  mkdir "${TARGET_DIR}"
fi

cd "${TARGET_DIR}" || exit 1
git clone --bare "${TARGET_REPO}" .git
echo "gitdir: ./.git" > .git
git worktree add main
